// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GAMEPADDRIVE_H
#define GAMEPADDRIVE_H


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "../ActionsRecorder.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class GamePadDrive: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	GamePadDrive();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

	// Update the vehicle based on the gamepad command
	void UpdateVehicle();
	// Update the catapult based on the gamepad command
	void UpdateCatapult();
	// Update the Winch based on the gamepad command
	void UpdateWinch();
	// Update the actions recorder base on the gamepad command
	void UpdateRecorder();
	// Update the gear gate based on the gamepad command
	void UpdateGearGate();

private:
	std::shared_ptr<Joystick> pJoystick;	// Used to access the joystick
	ActionsRecorder* pActionsRecorder;		// Used to record a sequence of actions
	bool btnTooggleRecordPressed;			// Used to avoid multiple calls in a same action (button pressure)
	bool btnTooglePlayPressed;				// Used to avoid multiple calls in a same action (button pressure)
	bool btnToggleGatePressed;				// Used to avoid multiple calls in a same action (button pressure)
	bool btnToggleWinchBreakPressed;		// Used to avoid multiple calls in a same action (button pressure)
	bool btnToggleStopCatapult;				// Used to avoid multiple calls in a same action (button pressure)
	bool btnToggleInvertDriveControl;		// Used to avoid multiple calls in a same action (button pressure)
	bool btnTooggleCycleSlotPressed;		// Used to avoid multiple calls in a same action (button pressure)
	bool btnTooggleSetAutonomousPressed;	// Used to avoid multiple calls in a same action (button pressure)
	bool btnToggleAgitatorPressed;			// Used to avoid multiple calls in a same action (button pressure)
	bool btnToggleAgitatorPanicPressed;			// Used to avoid multiple calls in a same action (button pressure)

	int currentRecorderSlot;				// Id of the current recorder slot
	double invertDriverControlCoef;			// Coef used to invert the driver command if necessary (i.e. we drive backward and like to have a forward feeling)

	Geargate::gatePosition posGearGate; 	// Used to toggle the gear gate position
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};

#endif
